name: Simple CI/CD 

on: [ push ]

env:
  ARTIFACT_NAME: output.txt

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test the Application
        run: python hello.py
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Upload artifacts
        run: python hello.py > output.txt
      - name: Create Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: output
          path: ./${{env.ARTIFACT_NAME}}
    