name: Simple CI/CD 

on: [ push ]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test the Application
        run: python hello.py
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Create Artifact
        uses: actions/checkout@v1
        run: python hello.py > output.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: output.txt
          path: output.txt
    